version: '3'
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/html

  app:
    build: ./docker/app
    volumes:
      - ./laravel:/var/www/html
    depends_on:
        - db

  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: sample
    ports:
      - "5432:5432"
